/**
 * Script to hold the "cart" class that will contain the item's information to pass to the database
 * 
 * Version 1.0
 * 
 * Author: Diego A. Ramirez, for R2 consulting
 * 
 * Date: 10/04/2017
 * 
 * Notice this is the development version
 */

/**
 * Class that corresponds to the header in the backend side
 */
var Header = function(parameters) {
    var ordNo; //Order number, generated by the database
    var cliNo; //Client number, to get from the session
    var facNo; //Plant number, to get from the session

    var ordStatus; //Status of order
    var ordDate; //Date of order, autogenerated
    var ordTotal; //How much the client will pay, will be decimal on DB
}

/**
 * Class that corresponds to the header in the backend side
 */

var OrderItem = function(orNo, orIt, prSku, name, pcs, price) {
    var ordNo = orNo; //Get from the header
    var ordItem = orIt; //Get from table
    var proSKU = prSku; //Identifier of the product
    var ordProName = name; //Number of product
    var ordPieces = pcs; //How many of each item was ordered
    var unitPrice = price; //Price of the item
    var ordTotal = unitPrice * ordPieces; //Total spent of that product
}